api_platform:
    title: LabOwl API Platform
    version: 1.0.0
    enable_docs: true
    enable_swagger: true
    # Good defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
    swagger:
         api_keys:
             JWT:
                name: Authorization
                type: header
