doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'

        profiling_collect_backtrace: '%kernel.debug%'
        options:
            # Enable nested transactions
            1002: "SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED"

    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true

        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        second_level_cache:
            enabled: true
            region_lock_lifetime: 60
            region_lifetime: 3600
            log_enabled: '%kernel.debug%'
            regions:
                write_rare:
                    # expire automatically after 10 days
                    lifetime: 864000
                    # let's use app's main cache pool
                    # (in my case it's using Redis)
                    cache_driver: { type: service, id: cache.app }

                append_only:
                    # expire automatically after 100 days
                    lifetime: 8640000
                    # let's use app's main cache pool
                    # (in my case it's using Redis)
                    cache_driver: { type: service, id: cache.app }
        result_cache_driver:
            type: 'service'
            id: 'doctrine.result_cache_provider'

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system

when@dev:
    doctrine:
        orm:
            auto_generate_proxy_classes: true
            proxy_dir: '%kernel.cache_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool
    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.system
                doctrine.system_cache_pool:
                    adapter: cache.system

    monolog:
        handlers:
            doctrine:
                type: stream
                path: '%kernel.logs_dir%/doctrine.log'
                channels: doctrine
                level: debug